AWSTemplateFormatVersion: "2010-09-09"
Description: Cloudformation-study


Parameters:
 KeyName:
  Type: AWS::EC2::KeyPair::KeyName
 EC2InstanceAMI:
  Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
  Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
 InstanceType:
  Type: String
  Default: t3.micro
  AllowedValues:
     - t3.micro
     - t3.small
 RdsMasterPassword:                    
    Type: String
    NoEcho: true
    Description: RDS master user password
  



Resources:
 myVPC:
  Type: AWS::EC2::VPC
  Properties:
   CidrBlock: 10.0.0.0/16
   EnableDnsSupport: true
   EnableDnsHostnames: true
  
   Tags:
      - Key: Name
        Value: Cloudformation-study-vpc

 myInternetGateway:
  Type: AWS::EC2::InternetGateway
  Properties:
    Tags:
      - Key: Name
        Value: Cloudformation-study-igw
       
 AttachGateway: 
  Type: AWS::EC2::VPCGatewayAttachment
  Properties:
   VpcId: !Ref myVPC
   InternetGatewayId: !Ref myInternetGateway

 PublicSubnetA:
  Type: AWS::EC2::Subnet
  Properties:
   VpcId: !Ref myVPC
   CidrBlock: 10.0.1.0/24
   MapPublicIpOnLaunch: true
   AvailabilityZone: !Select [0, !GetAZs '']
   Tags:
    - Key: Name
      Value: Cloudformation-study-public-subnet-a
 PublicSubnetB:
   Type: AWS::EC2::Subnet
   Properties:
    VpcId: !Ref myVPC
    CidrBlock: 10.0.2.0/24
    MapPublicIpOnLaunch: true
    AvailabilityZone: !Select [1, !GetAZs '']
    Tags:
    - Key: Name
      Value: Cloudformation-study-public-subnet-b

  

 PublicRouteTable:
  Type: AWS::EC2::RouteTable
  Properties:
   VpcId: !Ref myVPC
   Tags:
    - Key: Name
      Value: Cloudformation-study-public-rt

 PublicRoute:
  Type: AWS::EC2::Route
  DependsOn: AttachGateway
  Properties:
   RouteTableId: !Ref PublicRouteTable
   DestinationCidrBlock: 0.0.0.0/0
   GatewayId: !Ref myInternetGateway

 PublicSubnetRouteTableAssociationA:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
   SubnetId: !Ref PublicSubnetA
   RouteTableId: !Ref PublicRouteTable

 PublicSubnetRouteTableAssociationB:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
   SubnetId: !Ref PublicSubnetB
   RouteTableId: !Ref PublicRouteTable

 secGroupEC2:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: allow ssh
    VpcId: !Ref myVPC
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 153.175.16.24/32
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        SourceSecurityGroupId: !Ref secGroupALB
        Description: Allow 8080 from ALB SG
    SecurityGroupEgress:
      - IpProtocol: -1
        CidrIp: 0.0.0.0/0
      
    Tags:
      - Key: Name
        Value: cloudformation-study-sg1

 secGroupRDS:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: Allow MySQL 3306 from EC2 security group
    VpcId: !Ref myVPC
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupId: !Ref secGroupEC2
        Description: Allow MySQL from EC2 SG
    SecurityGroupEgress:
      - IpProtocol: -1
        CidrIp: 0.0.0.0/0
    Tags:
      - Key: Name
        Value: cloudformation-study-sg2
    
   
 secGroupALB:
    Type: AWS::EC2::SecurityGroup
    Properties:
     VpcId: !Ref myVPC
     GroupDescription: ALB HTTP 80 only
     SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: 80
         ToPort: 80
         CidrIp: 0.0.0.0/0
     SecurityGroupEgress:
       - IpProtocol: -1
         CidrIp: 0.0.0.0/0
     Tags:
      - Key: Name
        Value: cloudformation-study-alb-sg

 myEC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    ImageId: !Ref EC2InstanceAMI
    InstanceType: !Ref InstanceType
    KeyName: !Ref KeyName
    Monitoring: true
    SecurityGroupIds: 
     - !Ref secGroupEC2
    SubnetId: !Ref PublicSubnetA

    Tags:
      - Key: Name
        Value: Cloudformation-study-ec2
  
 PrivateSubnetA:
   Type: AWS::EC2::Subnet
   Properties:
     VpcId:  !Ref  myVPC
     CidrBlock: 10.0.11.0/24
     AvailabilityZone: !Select [0, !GetAZs '']
     Tags:
       - Key: Name
         Value: Cloudformation-study-private-subnet-A

 PrivateSubnetB:
  Type: AWS::EC2::Subnet
  Properties:
    VpcId: !Ref myVPC
    CidrBlock: 10.0.12.0/24
    AvailabilityZone: !Select [1, !GetAZs '']
    Tags:
       - Key: Name
         Value: Cloudformation-study-private-subnet-B

 
 RdsDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS DB Subnet Group
      SubnetIds:
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetB
      Tags:
        - Key: Name
          Value: rds-db-subnet-group
 RDSInstance:
   Type: AWS::RDS::DBInstance
   Properties:
    DBInstanceIdentifier: cloudformationstudyrds
    Engine: mysql
    DBInstanceClass: db.t3.micro
    EngineVersion: "8.0"
    AvailabilityZone: !Select [0, !GetAZs '']
    DBName: CloudformationStudyRDS
    MasterUsername: admin
    MasterUserPassword: !Ref RdsMasterPassword
    VPCSecurityGroups:
      - !Ref secGroupRDS
    DBSubnetGroupName: !Ref RdsDBSubnetGroup
    PubliclyAccessible: false
    AllocatedStorage: 20   
    MultiAZ: false
    BackupRetentionPeriod: 1
    DeletionProtection: false
    Tags:
      - Key: Name
        Value: Cloudformation-study-rds
 ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: "application"
      Scheme: "internet-facing"
      Name:  cloudformation-study-alb
      Tags:
        - Key: Name
          Value: Cloudformation-study-alb
      IpAddressType: ipv4
      Subnets:
        - !Ref PublicSubnetA
        - !Ref PublicSubnetB
       
      SecurityGroups:
        - !Ref secGroupALB

 ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
     LoadBalancerArn: !Ref ALB
     Port: 80
     Protocol: HTTP
     DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref ALBTargetGroup
  
 ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: cloudformation-study-alb-tg
      Port: 8080
      Protocol: HTTP
      Matcher:
        HttpCode: '200'
      VpcId: !Ref myVPC
      TargetType: instance
      Targets:
        - Id: !Ref myEC2Instance
          Port: 8080
      Tags:
        - Key: Name
          Value: cloudformation-study-alb-tg


 



Outputs:
 VPCId:
  Description: VPC ID
  Value: !Ref myVPC
 PublicSubnetId:
  Description: Public Subnet ID
  Value: !Ref PublicSubnetA
 EC2InstanceId:
  Description: EC2 Instance ID
  Value: !Ref myEC2Instance
 EC2PublicIP:
  Description: EC2 Public IP
  Value: !GetAtt myEC2Instance.PublicIp
 RdsEndpoint:
    Description: RDS endpoint address
    Value: !GetAtt RDSInstance.Endpoint.Address
 RdsPort:
    Description: RDS endpoint port
    Value: !GetAtt RDSInstance.Endpoint.Port
 ALBURL:
    Description: ALB endpoint URL
    Value: !Join
        - ""
        - - http://
          - !GetAtt ALB.DNSName
